version: "3.8"

services:
  redis:
    image: "redis:latest"
    container_name: "redis"
    ports:
      - "6379:6379"
  aiochat_server:
    build: "."
    container_name: "mysite"
    ports:
      - "8000:8000"
    links:
      - "redis"